import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Typography from "@mui/material/Typography"
import CreatePostPage from '@components/create-post/createpostpage'

const Category: NextPage = () => {
  return (
    <div>
      <Head>
        <title>New Post | Syed Mahbub&apos;s Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

    <CreatePostPage />
    </div>
  )
}

export default Category;
