import type { NextPage } from "next";
import Head from "next/head";
import CategoryPage from "@components/category-page/categorypage";
import axios from "axios";

type categoryProps = {
  data: any;
};

const CategoryPageHandler: NextPage<categoryProps> = (props) => {
  return (
    <div>
      <Head>
        <title>{props.data.name} | Syed Mahbub&apos;s Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <CategoryPage articles={props.data.articleIds} data={props.data} />
    </div>
  );
};

export async function getServerSideProps(context: any) {
  try {
    const url =
        process.env.NODE_ENV === "production"
          ? process.env.API_URI
          : "http://localhost:3000/api/v1/";
      const res: any = await axios.get(`${url}categories/${context.query.name}`, {
        headers: { "Content-Type": "application/json" },
        withCredentials: true,
      });
    const data: any = res.data.getArticles;
    if(!data){
      return {
        notFound: true
      }
    }
    return {
      props: {
        data,
      },
    };
  } catch (error: any) {
    console.error(error.response?.data ? error.response.data.message : error.message)
    return {
      notFound: true,
    };
  }
}

export default CategoryPageHandler;
