import type { NextPage } from "next";
import Head from "next/head";
import CategoryPage from "@components/category-page/categorypage";
import { engCategories, categories } from "@components/post/post-constants";
import API from "@api/API";

type categoryProps = {
  data: any;
};

const CategoryPageHandler: NextPage<categoryProps> = (props) => {
  return (
    <div>
      <Head>
        <title>{props.data.name} | Syed Mahbub&apos;s Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <CategoryPage articles={props.data.articles} data={props.data} />
    </div>
  );
};

export async function getServerSideProps(context: any) {
  const { name } = context.query;
  const indexOfName = engCategories.indexOf(name);
  const res: any = await API.get(`/categories/${categories[indexOfName]}`);
  const data: any = res.data.cat;
  if (!data) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      data,
    },
  };
}

export default CategoryPageHandler;
