import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Typography from "@mui/material/Typography"
import HomePage from '@components/home-page/homepage'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Syed Mahbub&apos;s blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <HomePage />
    </div>
  )
}

export default Home
